### ISSUE TITLE
Roth RC#1

### ISSUE THREAD

**Issue by ingen-lab** [ingen-lab/Ruth#30]
Basically the same steps as issue [#29 Ruth need further testing](https://github.com/Outworldz/Ruth/issues/29)

Any takers?

**Comment by mdickson** [comment]
I have committed to getting my scripts for the appliers done this week but I'll make some time to work through your list and review the blend file asap for RC3,

**Comment by Deledrius** [comment]
I don't see a `.dae` for Roth's RC1 in the repository.  Should we all be exporting our own to test this release candidate? That seems prone to error.  Which Roth `.blend` is the one we should be exporting for test purposes?
