### ISSUE TITLE
Ruth 2.0 RC3 Devkit non-functional

### ISSUE THREAD

**Issue by zauberparacelsus** [ingen-lab/Ruth#46]
The Ruth 2.0 RC3 devkit is non-functional.  Attempting to load it into Avastar produces an error saying that reading the file failed because it is not a .blend file.  The file extension is .blend, so the error actually means that it's not a *valid* .blend file.

file path: Ruth/Mesh/Avatar Ruth/Current Release/OSRuth2_CurrentRelease_DevKit_RC3.blend

Attempting to open the devkit directly in blender causes it to give a "file format not supported" error.  If opened from the file system, it opens blender with whatever you have as the default scene.

**Comment by Outworldz** [comment]
I cannot reproduce.  I can see thumbnails as well.   Blender 2.79b. Avastar Bento 2.4.1
![image1](https://user-images.githubusercontent.com/1253433/51197169-62ab0380-18b6-11e9-87e9-692f833250e0.png)

**Comment by zauberparacelsus** [comment]
Okay, I am going to re-download the file in case it somehow got corrupted.
